#!/bin/bash

VM=$(zenity --list --title="Sistemas operacionais" --text="" --column="Máquinas Virtuais" "Ubuntu" "Windows")

if [ "$VM" == "Ubuntu" ]; then
    xfreerdp /v:10.25.1.19 /u:maq2 /p:maq2 /f +clipboard
elif [ "$VM" == "Windows" ]; then
    xfreerdp /v:10.25.2.80 /u:maq1 /p:maq1 /f +clipboard
else
    zenity --error --text="Nenhuma VM selecionada."
    exit 1
fi

